// <auto-generated />
using System;
using DailySpendServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DailySpendServer.Data.Migrations
{
    [DbContext(typeof(DailySpendContext))]
    [Migration("20260125141426_AddTablesAndFields")]
    partial class AddTablesAndFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("DailySpendServer.Model.BankAccount", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<long>("Balance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaskedPan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserSettingId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WebHookUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("UserSettingId")
                        .IsUnique();

                    b.ToTable("BankAccounts");
                });

            modelBuilder.Entity("DailySpendServer.Model.DailyPlan", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlannedAmount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SpentAmount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserSettingId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("UserSettingId");

                    b.ToTable("DailyPlans");
                });

            modelBuilder.Entity("DailySpendServer.Model.Notification", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Balance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSent")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserSettingId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("UserSettingId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("DailySpendServer.Model.UserEventMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserEventMessage");
                });

            modelBuilder.Entity("DailySpendServer.Model.UserSetting", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BankAccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DailyPlanId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GoalAmount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastWebhookReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NotificationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedAccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("WebHookActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WebHookSecret")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("daysToSalary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("DailySpendServer.Model.BankAccount", b =>
                {
                    b.HasOne("DailySpendServer.Model.UserSetting", "UserSetting")
                        .WithOne("BankAccount")
                        .HasForeignKey("DailySpendServer.Model.BankAccount", "UserSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserSetting");
                });

            modelBuilder.Entity("DailySpendServer.Model.DailyPlan", b =>
                {
                    b.HasOne("DailySpendServer.Model.UserSetting", "UserSetting")
                        .WithMany("DailyPlans")
                        .HasForeignKey("UserSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserSetting");
                });

            modelBuilder.Entity("DailySpendServer.Model.Notification", b =>
                {
                    b.HasOne("DailySpendServer.Model.UserSetting", "UserSetting")
                        .WithMany("Notifications")
                        .HasForeignKey("UserSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserSetting");
                });

            modelBuilder.Entity("DailySpendServer.Model.UserEventMessage", b =>
                {
                    b.HasOne("DailySpendServer.Model.UserSetting", "UserSetting")
                        .WithMany("UserEventMessages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserSetting");
                });

            modelBuilder.Entity("DailySpendServer.Model.UserSetting", b =>
                {
                    b.Navigation("BankAccount");

                    b.Navigation("DailyPlans");

                    b.Navigation("Notifications");

                    b.Navigation("UserEventMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
