// <auto-generated />
using System;
using DailySpendServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DailySpendServer.Data.Migrations
{
    [DbContext(typeof(DailySpendContext))]
    partial class DailySpendContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("DailySpendServer.Model.BankAccount", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Balance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CashbackType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaskedPan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserSettingId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WebHookUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("cardId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("UserSettingId")
                        .IsUnique();

                    b.ToTable("BankAccounts");
                });

            modelBuilder.Entity("DailySpendServer.Model.DailyPlan", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlannedAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpentAmount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserSettingId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("UserSettingId");

                    b.ToTable("DailyPlans");
                });

            modelBuilder.Entity("DailySpendServer.Model.UserSetting", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BankAccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DailyPlanId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GoalAmount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedAccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("daysToSalary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("DailySpendServer.Model.BankAccount", b =>
                {
                    b.HasOne("DailySpendServer.Model.UserSetting", "UserSetting")
                        .WithOne("BankAccount")
                        .HasForeignKey("DailySpendServer.Model.BankAccount", "UserSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserSetting");
                });

            modelBuilder.Entity("DailySpendServer.Model.DailyPlan", b =>
                {
                    b.HasOne("DailySpendServer.Model.UserSetting", "UserSetting")
                        .WithMany("DailyPlans")
                        .HasForeignKey("UserSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserSetting");
                });

            modelBuilder.Entity("DailySpendServer.Model.UserSetting", b =>
                {
                    b.Navigation("BankAccount");

                    b.Navigation("DailyPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
